#!/usr/bin/env node
/**
 * runner/generate_daily_report.js — produce daily/belief_report_YYYY-MM-DD.md
 *
 * Reads: state/ontology.json, state/belief_state.json, journals/<today>_*.html
 * Writes: daily/belief_report_YYYY-MM-DD.md
 *
 * Called once per day from run.sh at the daily-maintenance trigger.
 * Non-fatal: exits 0 on any error after logging.
 */

"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT       = path.resolve(__dirname, "..");
const DAILY_DIR  = path.join(ROOT, "daily");
const ONTO       = path.join(ROOT, "state", "ontology.json");
const BELIEF     = path.join(ROOT, "state", "belief_state.json");
const JOURNALS   = path.join(ROOT, "journals");

const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

function loadJson(p) {
  try { return JSON.parse(fs.readFileSync(p, "utf-8")); } catch { return null; }
}

function todayJournalCount() {
  try {
    return fs.readdirSync(JOURNALS).filter(f => f.startsWith(today) && f.endsWith(".html")).length;
  } catch { return 0; }
}

(function main() {
  try {
    const onto   = loadJson(ONTO);
    const belief = loadJson(BELIEF);

    const axes     = onto?.axes || [];
    const activeAxes = (belief?.axes || []).filter(a => (a.confidence || 0) > 0);
    const journals = todayJournalCount();

    if (!fs.existsSync(DAILY_DIR)) fs.mkdirSync(DAILY_DIR, { recursive: true });

    const outPath = path.join(DAILY_DIR, `belief_report_${today}.md`);

    // Build axes section
    const axesLines = axes.map(a => {
      const evidenceCount = (a.evidence_log || []).length;
      const scoreBar = scoreToBar(a.score ?? 0);
      const confPct  = ((a.confidence ?? 0) * 100).toFixed(0);
      return [
        `### ${a.label}`,
        `- ID: \`${a.id}\``,
        `- Score: ${(a.score ?? 0).toFixed(4)}  ${scoreBar}`,
        `- Confidence: ${confPct}%`,
        `- Evidence entries: ${evidenceCount}`,
        `- Left pole: ${a.left_pole || "(not set)"}`,
        `- Right pole: ${a.right_pole || "(not set)"}`,
      ].join("\n");
    }).join("\n\n");

    const highConf = activeAxes
      .sort((a, b) => (b.confidence || 0) - (a.confidence || 0))
      .slice(0, 3)
      .map(a => `- \`${a.id}\`: conf ${((a.confidence || 0) * 100).toFixed(0)}%, score ${(a.score || 0).toFixed(3)}`)
      .join("\n") || "- (none with confidence > 0 yet)";

    const report = `---
date: "${today}"
title: "Belief Report — ${today}"
---

# Belief Report — ${today}

**Generated:** ${new Date().toISOString()}
**Journals written today:** ${journals}
**Total axes tracked:** ${axes.length}

---

## Highest-confidence axes

${highConf}

---

## Full ontology snapshot

${axesLines || "(no axes yet)"}

---

*This report was auto-generated by generate_daily_report.js from state/ontology.json and state/belief_state.json.*
`;

    fs.writeFileSync(outPath, report, "utf-8");
    console.log(`[daily_report] written: daily/belief_report_${today}.md (${axes.length} axes)`);
  } catch (err) {
    console.error(`[daily_report] failed: ${err.message}`);
    process.exit(0); // non-fatal
  }
})();

/** Convert score [-1, +1] to a simple ASCII directional bar. */
function scoreToBar(score) {
  const pct = Math.round((score + 1) / 2 * 10); // 0-10
  const filled = Math.min(10, Math.max(0, pct));
  return `[${"█".repeat(filled)}${"░".repeat(10 - filled)}] (L${" ".repeat(10)}R)`;
}
